Davidobot/BetterJoy

- BetterJoyForCemu/Joycon.cs
On some original Nintendo controllers gyro drift occurs (moves
constantly to the right, for example).
Not dividing the neutral point by 2 seems to fix the problem, and
it doesn't seem to effect other controllers negatively (tested
with 8bitDo N30 pro and SF30 Pro).
> prevent gyro drift on some controllers

- BetterJoyForCemu/Joycon.cs
I was using two Joycons as a single controller. One (often right, sometimes
both, sometimes left) of the Joycons seems to have random lags.
This patch reliably removes the lag for me.
Potentially fixes #32.
More context:
I first excluded the possibility that the Bluetooth connection is lagging,
because when I click the "locate" button, both Joycons can rumble
immediately without lag.
Reading the existing issues seems to suggest something was wrong with
threading. When I tried moving both Joycons' "Poll" to a single thread,
by calling both ReceiveRaw() and other.ReceiveRaw() in a single Joycon
Poll thread, and removing "lock { ...}"s), lag still exists.
I then suspected the I/O loop is too busy so the code does not have time
to consume events in time. By adding some debug prints, I was …
>  SendRumble less frequently to reduce input lag

- BetterJoyForCemu/Joycon.cs
When rumble_obj.t >= 0, SendRumble should be frequently called to make
Rumbling actually work.
> Fix Rumble feature for bluetooth devices

- BetterJoyForCemu/Joycon.cs
Hey there.
TL;DR;
There was an overflow at some edge case when converting from the float [-1, 1]~ish value to the short [-2^15, 2^15 - 1] value for the sticks. This commit fixes it.
Not TL;DR;
When casting from float to short, most casts were "guarded" by min-max correction before casting, however some weren't guarded properly, causing the cast to yield the wrong value.
Below is a code sample showing why it happened. It mostly has to do with how casting works from higher precision types to lower precision ones.
The specific place the code fails is when in the single joy-con mode the resulting float value is multiplied by -1 before being cased to short. In the case the float value was `Int16.MinValue` (being -32768) it will result in a value of 32768, which is equal to `Int16.MaxValue` …
> Fix stick casting overflow.

- BetterJoyForCemu/MainForm.cs
I don't know if it was intended or not, but when minimizing the window stayed as a tool window on the desktop, which is a bit weird in my opinion. With this the window now fully hides when minimizing.
> Hide window instead of showing as tool window on desktop

- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/MainForm.resx
- BetterJoyForCemu/Program.cs
When using two joycon as one joined controller, now both joycon show the same player LED, like on the Switch.
> Same joycon LEDs when joined

- BetterJoyForCemu/3rdPartyControllers.cs
More specifically, the exception:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
at CallSite.Target(Closure , CallSite , Object , String )
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
at BetterJoyForCemu._3rdPartyControllers.ContainsText(ListBox a, String manu)
at BetterJoyForCemu._3rdPartyControllers.RefreshControllerList()
at BetterJoyForCemu._3rdPartyControllers..ctor()
at BetterJoyForCemu.MainForm.btn_open3rdP_Click(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, …
```
> Fix exception when pressing Add Controllers button

- BetterJoyForCemu/App.config
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/Program.cs
Hi.
I've implemented a couple of simple power-off feature(s) for JoyCons.
1. **AutoPowerOff**: automatically power off joycons at program exit
2. **HomeLongPowerOff**: power off joycons when Home (right only joycon or combined joycons) or Capture (left only joycon) button is pressed for a long interval (hard-coded to 2s)
In order to detect long-presses of the Home/Capture buttons I've added some basic timestamp tracking for when buttons are pressed.
Tested only on JoyCons, not Pro nor SNES controller.
> JoyCons power-off feature

- BetterJoyForCemu/Joycon.cs
fixes #344 by reading (and discarding) all but the latest available HID data. it appears to be bufffered somewhere.
- ~~[ ] Handle Timestamp for motion data better~~
> Fix input delay

- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/Program.cs
Only send rumble data when needed
The issue with having to send rumble data in order to get new input reports seems to have been a issue with the attach procedure for USB
should probably fix the remaining usb/rumble related issues #398 #397
> Only send rumble data when needed

- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/Program.cs
Instead of re requesting spi data we will now simply wait for the correct response and discard all others. This is far from perfect but a vast improvement over how it used to work.
this PR builds upon #408
fixes #412
> Improve fetching subcommand response

- BetterJoyForCemu/Program.cs
Without `ptr` being reassigned in the case of a 0 `prod_id`, the app would get into an infinite loop on launch, before opening- this should resolve it 😊
> 🐛 avert infinite loop when prod_id not assigned

- BetterJoyForCemu/App.config
- BetterJoyForCemu/Config.cs
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/Reassign.Designer.cs
- BetterJoyForCemu/Reassign.cs
- README.md
Adds support for a Shake input.
Tested with the Switch pro controller.
Needs to be tested with Joy-cons
Only supports DS4 because Xinput does not have any free buttons to use.
Remaps the Touchpad input (Button 13 on DirectInput) to use the new Shake input.
Added 3 new options to settings:
1. Enable the shake input.
2. Change the shake detection sensitivity.
3. Change how often the shake input can run.
> Inital change for #518

- BetterJoyForCemu/App.config
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/Program.cs
This adds a new option to calibrate controllers in BetterJoy.
Separates the calibration code from the Non-Original Controller setting.
Do not merge yet, this still needs to be tested by someone with access to Joy-cons.
Tested with the Switch Pro Controller.
Should be merged with #520 as it also contains calibration fixes.
> new option to calibrate controllers in BetterJoy

- BetterJoyForCemu/MainForm.cs
We don't need to parse the `NonOriginalController` for the `nonOriginal` variable so we remove it.
> Remove unnecessary code.

- BetterJoyForCemu/App.config
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/Program.cs
This aims to fix issues where BetterJoy would lose rumble packets due to many packets being received at very short intervals (sub 6 ms) which would cause the rumble to not rumble at all or would not stop rumbling.
This PR fixes this issue by adding a Queue/Buffer for the rumble packets enabling BetterJoy to process the data properly and in the correct order.
It also removes the need to have a `Rumble Delay` setting because it will start and stop the rumble according to the data received.
Since the configurable rumble duration is not available anymore, the `Locate` button will use a delay to set the Rumble.
> Rumble data processing refactor

- BetterJoyForCemu/BetterJoy.csproj
- BetterJoyForCemu/Collections/ConcurrentList.cs
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/Program.cs
- BetterJoyForCemu/UpdServer.cs
Connecting 4 Joycons presented issues.
The first two pair successfully, then the third would sit idle as the fourth connected Joycon would connect to the first.
The on-connect pairing will now correctly ignore a Joycon if it is already paired/connected to another Joycon.
This also fixes crashes when using 3-4+ Joycons as the List implementation did not previously support multiple threaded access.
> Do not connect Joycons that are already paired. Fix concurrent modification crash.

- BetterJoyForCemu/3rdPartyControllers.cs
- BetterJoyForCemu/Program.cs
This fixes the ability to [change the type of a 3rd party JoyCon](https://github.com/Davidobot/BetterJoy/issues/646) as described also [here](https://github.com/Davidobot/BetterJoy/issues/588#issuecomment-758769386).
I noticed that 3rd party joycons (in my case joysky "wireless controller for N/SW") reported the same name "wireless gamepad" and vendor id to windows for Left and Right Joycon. 
BetterJoy is using this args for generating a unique id for 3rdParty configuration that results the same for Left/Right.
**3rdPartyControllers** file content in **6.4a version**:
_Wireless Gamepad|1406|8201|2
Wireless Gamepad|1406|8201|3_
**3rdPartyControllers** file content in **current master**:
_Wireless Gamepad(1406-8201)|1406|8201|2
Wireless Gamepad(1406-8201)|1406|8201|3_
In both cases the …
> used serial_number to identify and set type to a specific device

- BetterJoyForCemu/Config.cs
This PR fixes a bug where, for some reason, BetterJoyForCemu tries to look for the `settings` file under `C:/WINDOWS/system32` when launching the executable from Search, or under the PowerToys install directory from PowerToys Run.
> Fix settings file not being able to be found when launching BetterJoyForCemu from Search/PowerToys Run

- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/UpdServer.cs
I attempted to use a single joycon with Dolphin over the MotionServer (DSUClient) in 6.4b and noticed the SL and SR buttons were not available. Unlike in other places, the code for the MotionServer doesn't adapt to single vs. pro or double joycon, it seems to be hardcoded. This change fixes that by re-using the logic used for mapping the joycon input to a DS4 controller, then using that DS4 mapping to build the MotionServer information. 
In fixing this I noticed the DS4 mapping was abit broken to begin with, likely due to a simple copy/paste error that breaks the square and ps button inputs in single joycon mode. So also included in this pull request is a fix for that.
> MotionServer DS4 mapping

- BetterJoyForCemu/Program.cs
Fix https://github.com/Davidobot/BetterJoy/issues/788
As discussed in
[Using SetDefaultDllDirectories breaks Font handling](https://stackoverflow.com/questions/25818073/using-setdefaultdlldirectories-breaks-font-handling)
it is not a good idea to use `SetDefaultDllDirectories`, luckily kjbartel gave us a solution.
> fix hidapi.dll loading

- BetterJoyForCemu/Joycon.cs
These changes perform 2 functions:
- Fix Dualshock 4 outputs ZL -> L2 and ZR -> R2 not working in many games (implement digital buttons) - the issue here was that on a real DS4, the L2 / R2 triggers are both analog _and_ digital.  They throw analog axis values until they are nearly fully depressed, then they _also_ fire a digital button when they are fully depressed.  The current implementation prior to this pull request does not ever fire the digital buttons, which makes many games, which only poll for the digital trigger buttons, to not see the triggers as pulled (as an example, web-slinging in Spider-Man, or grabbing your pack in Death Stranding).  Fixes https://github.com/Davidobot/BetterJoy/issues/715 and https://github.com/Davidobot/BetterJoy/issues/559.
- Remap "Capture" button in …
> Fix DS4 L2 / R2 not working in many games and remap capture -> share / minus -> touchpad

- README.md
When I tried to build the project locally in order to debug a Joycon disconnection, I had many issues figuring out the various steps for building correctly the app.
This pull request add the appropriate information in order to allow others to build the project.
> Add building instructions
