- .gitignore
- BetterJoyForCemu/BetterJoyForCemu.csproj
- BetterJoyForCemu/Config.cs
- BetterJoyForCemu/MainForm.Designer.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/packages.config
This pull request adds an option in settings and a checkbox in the main form for configuring the app to start minimized in tray.
This also adds a proper nuget dependency for ViGEmClient.  Without this, it is not possible to build the solution.
> Add option to start the application minimized to tray

- BetterJoyForCemu/App.config
- BetterJoyForCemu/Config.cs
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/MainForm.Designer.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/Program.cs
This PR could solve most non-original pro controller usability problem.
With my poor English level, the prompt console text such as in [MainForm.cs](https://github.com/xqdoo00o/BetterJoyForCemu/blob/master/BetterJoyForCemu/MainForm.cs#L325) maybe not so accurate. And the code indent too.
> feat for non-original controller

- README.md
Updated link to new ViGEm repository in README
> Updated orphaned ViGEm link

- BetterJoyForCemu/Joycon.cs
> fixes cpu busy spinning when there is no hid data available

- BetterJoyForCemu/BetterJoy.csproj
- BetterJoyForCemu/Controller/OutputControllerDualShock4.cs
- BetterJoyForCemu/Controller/OutputControllerXbox360.cs
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/Program.cs
This PR reverts the previous input delay fix, the cpu fix that followed and now introduces a state diffing for when to push new data to x360 and DS4 controllers. At least for me this also solves the latency issues.
should fix #353
> Fix input delay 2

- BetterJoyForCemu/.editorconfig
- BetterJoyForCemu/Config.cs
- BetterJoyForCemu/Controller/OutputControllerDualShock4.cs
- BetterJoyForCemu/Controller/OutputControllerXbox360.cs
- BetterJoyForCemu/HIDapi.cs
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/Program.cs
- BetterJoyForCemu/UpdServer.cs
This adds a .editorconfig file that will ensure all contributors use the same formatting options.
I recommend using https://marketplace.visualstudio.com/items?itemName=mynkow.FormatdocumentonSave 
to ensure they're applied to all documents you modify.
I some future change i might look into doing this automatically as a pre-commit hook.
Feel free to change any setting, I've mostly used the default and tried to make them match the existing style.
> Formatting

- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/Program.cs
Reverts Davidobot/BetterJoy#408
> Revert "Only send rumble data when needed"

- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/Program.cs
These changes mitigates a whole host of multi threading issues. Some of them where introduced when I changed the Subcommand, others have been here for a while.
with these changes the app won't lock up if you try to start it with things plugged in.
> avoids some multi threading issues

- BetterJoyForCemu/Controller/OutputControllerDualShock4.cs
Fixed button translation error from OutputControllerDualShock4 to IDualShock4Controller
> Fixed button translation error

- BetterJoyForCemu/Config.cs
This fixes issue #519  
Make sure to delete the settings file first before testing.
> Fixes #519

- BetterJoyForCemu/MainForm.Designer.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/MainForm.resx
The settings text were clipped before, this fixes that.
> Change the width of the settings menu

- BetterJoyForCemu/Joycon.cs
> Fix accelerometer axis to have correct data for orientation

- BetterJoyForCemu/App.config
- BetterJoyForCemu/Joycon.cs
This PR aims to allow users to enable debug logs and be able to give that information to the devs.
Added a `Debug Type` to the App config and added documentation to it.
Make BetterJoy read the data from the configuration and switch between debug modes accordingly.
> Expose debugging parameters

- BetterJoyForCemu/Joycon.cs
This PR fixes an issue where the Rumble queue was not cleared when receiving a lot of data.
> Fix dequeuing

- BetterJoyForCemu/App.config
- BetterJoyForCemu/Joycon.cs
- BetterJoyForCemu/MainForm.cs
- BetterJoyForCemu/Program.cs
- BetterJoyForCemu/UpdServer.cs
Also consolidates LED and other/attached Joycon handling.
> Use incremental lighting to indicate players on Joycons.

- BetterJoyForCemu/3rdPartyControllers.cs
Pretty much the same issue as the one mentioned in #673.
> Fix 3rdPartyControllers file not being able to be found when launching BetterJoyForCemu from Search/PowerToys Run

- BetterJoyForCemu/Joycon.cs
the mapping to ds4 when using combined joycon was faulty; this should be correct but I currently have no way to test it
> Fix incorrect button mapping to DS4

- BetterJoyForCemu/BetterJoy.csproj
- BetterJoyForCemu/Program.cs
- BetterJoyForCemu/Reassign.cs
- BetterJoyForCemu/packages.config
Potential fix for #657. Tested on my machine and seems to solve the issue.
> Bump WindowsInput version

- README.md
in my experience it tends to not work before a restart
> mention rebooting

- BetterJoyForCemu/Program.cs
as discussed in https://github.com/Davidobot/BetterJoy/issues/882
> Float Parsing issue fix
